apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-health-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-health-api
  template:
    metadata:
      labels:
        app: network-health-api
    spec:
      containers:
        - name: api
          image: network-health-api-api:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          # ----------------------
          # environment variables
          # ----------------------
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres-db:5432/postgres

            - name: ENV
              value: "prod"

          # ----------------------
          # health probes
          # ----------------------
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10

          # ----------------------
          # resources
          # ----------------------
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

